### ISSUE TITLE
Sileo Removal Repo

### ISSUE THREAD

**Issue by BananaManCJ** [Greigh/iOS-Jailbreak-Master-Repository#1]
The repo with the tool to remove sileo (https://repo.x4-applegate.com/) doesn't work and should probably be removed

**Comment by Greigh** [comment]
What error are you getting?

**Comment by Greigh** [comment]
Updated and removed as of [63c07f6](https://github.com/Greigh/iOS-Jailbreak-Master-Repository/commit/63c07f654c6a9d186776d84353643bcd36ffd6da).
