### ISSUE TITLE
Repo deprecated: https://zx02.yourepo.com/

### ISSUE THREAD

**Issue by sunmono** [Greigh/iOS-Jailbreak-Master-Repository#2]
https://zx02.yourepo.com/ (General Repos) says it’s deprecated; new repo is https://tiny.cc/zx02/

**Comment by Greigh** [comment]
Thank you! Updated as of [0cd72d265673cca4ec66559f87d7057079269a88](https://github.com/Greigh/iOS-Jailbreak-Master-Repository/commit/0cd72d265673cca4ec66559f87d7057079269a88).
